<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Foreman</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.15.6755" />
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ForemanTest" />
    <InternalsVisibleTo Include="Foreman.Mac" />
    <InternalsVisibleTo Include="Foreman.Mac.UiTests" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Graphics/BurnerGeneratorIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/ElectricityIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/ErrorIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/ExtraGroupIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/HeatIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/PlantAssembler.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/PlayerAssembler.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/RocketAssembler.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/SpoilAssembler.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Graphics/UnknownIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Mods/foremanexport_2.0.0/**" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Mods/foremansavereader_2.0.0/**" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="baseCustom.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
